name: Generate Snake
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 1 * * *"   # daily at 01:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main (just for workflow context)
        uses: actions/checkout@v4

      - name: Checkout output branch
        uses: actions/checkout@v4
        with:
          ref: output
          path: out

      - name: Build snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: Abir7109
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Merge Snake SVGs into output folder
        run: |
          mkdir -p out
          cp -f dist/github-snake*.svg out/ || true

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: out
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
