name: Generate Snake
on:
  schedule:
    - cron: "0 1 * * *"   # daily at 01:00 UTC
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Build snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: Abir7109
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
